import express from "express";
import cors from "cors";
import multer from "multer";

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

app.use(cors());
app.use(express.json());

// ──────────────────────────────────────────────
// FREE TEXT API (Mocked for Prototype)
// ──────────────────────────────────────────────
app.post("/api/enhance-text", async (req, res) => {
  const { prompt } = req.body;
  if (!prompt) return res.status(400).json({ error: "Prompt is required" });

  try {
    // We simulate an AI processing the prompt and enhancing it.
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate API delay

    const lowerPrompt = prompt.toLowerCase();
    
    // Simple heuristic-based enhancement
    let tone = "Neutral";
    if (lowerPrompt.includes("dark") || lowerPrompt.includes("night")) tone = "Cinematic & Moody";
    else if (lowerPrompt.includes("bright") || lowerPrompt.includes("sun")) tone = "Vibrant & Warm";
    else if (lowerPrompt.includes("dream") || lowerPrompt.includes("magic")) tone = "Ethereal & Dreamy";

    let intent = "Create a high-quality visualization";
    let style = "Digital Art";
    if (lowerPrompt.includes("photo")) style = "Photorealistic";
    else if (lowerPrompt.includes("paint")) style = "Oil Painting";
    else if (lowerPrompt.includes("anime")) style = "Anime / Cell-shaded";

    const enhancedPrompt = `A stunning, high quality masterpiece of ${prompt}. Highly detailed, 8k resolution, trending on artstation, unreal engine 5 render, ${tone.toLowerCase()} lighting, ${style.toLowerCase()} style.`;

    const parsed = {
      analysis: {
        tone,
        subject: prompt.substring(0, 50) + (prompt.length > 50 ? "..." : ""),
        style,
        intent
      },
      enhancedPrompt,
      suggestedStyles: ["Photorealistic", "Digital Art", "Cinematic"]
    };

    res.json({ success: true, data: parsed });
  } catch (err) {
    console.error("Enhance text error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ──────────────────────────────────────────────
// FREE IMAGE GENERATION via Pollinations.ai (No API key needed)
// ──────────────────────────────────────────────
app.post("/api/generate-image", async (req, res) => {
  const { prompt, style } = req.body;
  if (!prompt) return res.status(400).json({ error: "Prompt is required" });

  try {
    const finalPrompt = style ? `${prompt}. Art style: ${style}` : prompt;
    
    // Extract actual meaningful nouns from prompt for the free photo service
    const stopWords = ['a','an','the','of','in','on','at','for','to','with','beautiful','stunning','cinematic','remake','high','quality','masterpiece','highly','detailed','resolution','trending','unreal','engine'];
    const keywords = prompt
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(w => w.length > 2 && !stopWords.includes(w))
      .slice(0, 2)
      .join(",") || "abstract";

    const cacheBuster = Math.floor(Math.random() * 1000);
    const url = `https://loremflickr.com/1024/1024/${encodeURIComponent(keywords)}?lock=${cacheBuster}`;

    res.json({
      success: true,
      data: {
        url: url,
        revisedPrompt: "Generated by free conceptual photo API based on: " + keywords,
      },
    });
  } catch (err) {
    console.error("Generate image error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ──────────────────────────────────────────────
// FREE VISION API (Mocked for Prototype)
// ──────────────────────────────────────────────
app.post("/api/analyze-image", upload.single("image"), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "Image is required" });

  try {
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate analysis delay

    // Try to guess the subject from the file name to make the mock prompts relevant
    let defaultSubject = "scene";
    if (req.file && req.file.originalname) {
      const name = req.file.originalname;
      const baseName = name.substring(0, name.lastIndexOf('.')).replace(/[-_]/g, ' ').replace(/[0-9]/g, '').trim();
      if (baseName.length > 2) defaultSubject = baseName.toLowerCase();
    }

    const parsed = {
      caption: `An intriguing visual composition showing ${defaultSubject} structural elements.`,
      objects: ["Main Subject", "Background Details", "Lighting Sources"],
      mood: "Dynamic and expressive",
      colorPalette: ["Primary Color", "Accent Tone", "Deep Contrast"],
      style: "Cinematic Photography",
      theme: "Creative Exploration",
      composition: "Rule of thirds",
      variationPrompts: [
        `A beautiful cinematic remake of the ${defaultSubject}, changing the time of day to golden hour.`,
        `A cyberpunk futuristic re-interpretation of the ${defaultSubject} with glowing neon lights.`,
        `A highly detailed watercolor painting version of the ${defaultSubject}, ethereal lighting.`
      ]
    };

    res.json({ success: true, data: parsed });
  } catch (err) {
    console.error("Analyze image error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ──────────────────────────────────────────────
// FREE VARIATION GENERATION via Pollinations.ai
// ──────────────────────────────────────────────
app.post("/api/generate-variation", async (req, res) => {
  const { variationPrompt, analysis } = req.body;
  if (!variationPrompt) return res.status(400).json({ error: "Variation prompt is required" });

  try {
    const contextPrompt = analysis
      ? `${variationPrompt}. Inspired by original image with mood: ${analysis.mood}, style: ${analysis.style}, theme: ${analysis.theme}.`
      : variationPrompt;

    // Use the core subject keyword to retrieve an extremely accurate placeholder image
    const stopWords = ['a','an','the','of','in','on','at','for','to','with','beautiful','stunning','cinematic','remake','original','scene','changing','time','day','golden','hour','cyberpunk','futuristic','re-interpretation','image','glowing','neon','lights','highly','detailed','watercolor','painting','version','ethereal','lighting'];
    const keywords = variationPrompt
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(w => w.length > 2 && !stopWords.includes(w))
      .slice(0, 2)
      .join(",") || "abstract";

    const cacheBuster = Math.floor(Math.random() * 1000);
    const url = `https://loremflickr.com/1024/1024/${encodeURIComponent(keywords)}?lock=${cacheBuster}`;

    res.json({
      success: true,
      data: {
        url: url,
        revisedPrompt: "Variation photo matching core concepts: " + keywords,
      },
    });
  } catch (err) {
    console.error("Generate variation error:", err);
    res.status(500).json({ error: err.message });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`🍐 Pear Media free server running on http://localhost:${PORT}`));
